<?php if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
    <?= /** @var \Icinga\Module\X509\Paginator $paginator */ $paginator->render() ?>
    <div class="sort-controls-container">
        <?= $this->limiter ?>
        <?= $this->sortBox ?>
    </div>
    <?= $this->filterEditor ?>
</div>
<?php endif ?>
<table class="common-table table-row-selectable" data-base-target="_next">
    <thead>
        <tr>
            <th><?= $this->translate('First Name') ?></th>
            <th><?= $this->translate('Last Name') ?></th>
            <th><?= $this->translate('Email') ?></th>
            <th><?= $this->translate('CNIC') ?></th>
            <th><?= $this->translate('Phone Number') ?></th>
            <th><?= $this->translate('Address') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($list as $l): ?>
        <tr>
            <td><?= $l['firstname']?></td>
            <td><?= $l['lastname']?></td>
            <td><?= $l['email']?></td>
            <td><?= $l['cnic']?></td>
            <td><?= $l['phn_number']?></td>
            <td><?= $l['residental_address']?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
    </table>


